apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: vote
spec:
  type: ClusterIP
  ports:
  - name: "mongo-service"
    port: 27017
    targetPort: 27017
  selector:
    app: mongo
