apiVersion: v1
kind: Service
metadata:
  labels:
    app: node
  name: node
  namespace: vote
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 8080
    targetPort: 80
    nodePort: 31000
  selector:
    app: node

